# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0007_auto_20180103_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
