# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0009_auto_20180107_2008'),
        ('flexer', '0009_auto_20180107_2021'),
    ]

    operations = [
    ]
