# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0012_auto_20180111_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(default='16323a7a8c104e13bdf33bb50217822d', on_delete=django.db.models.deletion.CASCADE, to='flexer.Project'),
            preserve_default=False,
        ),
    ]
