# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0013_task_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='Testitie 13', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='Kolari', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='testi@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='+3581234567', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Description goes here', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='total_hours',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
