# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0015_client_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flexer.Project'),
        ),
    ]
