# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0016_auto_20180114_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flexer.Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
