# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0018_remove_project_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
